repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: \.md$
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: gitmoji-merge-commit-msg
        name: Gitmoji Merge Commit Message Modifier
        description: This hook automatically prepends the 🔀 emoji to merge commit messages to comply with gitmoji standards.
        entry: git_hooks/prepare-commit-msg
        language: script
