#!/bin/sh

commit_msg_file="$1"
commit_source="$2"

echo "commit_msg_file: $commit_msg_file"
echo "commit_source: $commit_source"
echo "\$3: $3"
echo

if [ "$commit_source" = "merge" ]; then
    target_branch=$(git rev-parse --abbrev-ref HEAD)
    parent_commits=$(git show -s --pretty=%P HEAD)

    echo "target_branch: $target_branch"
    echo "parent_commits: $parent_commits"
    
    source_commits=$(echo $parent_commits | awk '{print $2}')
    echo "source_commits: $source_commits"

    parent_branch=$(git show-branch -a 2>/dev/null | grep '\*' | grep -v "$(git rev-parse --abbrev-ref HEAD)" | head -n1 | sed 's/.*\[//; s/\].*//; s/[\^~][0-9]*//g')
    echo "parent_branch: $parent_branch"

    if [ -n "$parent_branch" ]; then
        echo "🔀 Merge branch '$parent_branch' into $target_branch" > "$commit_msg_file"
    else
        echo "source_commits is empty, skip commit message modification"
    fi
fi
